# Generated by Django 5.2 on 2025-04-12 07:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=30)),
                ('data_fabricacao', models.DateField()),
                ('data_validade', models.DateField()),
                ('quantidade_frascos', models.PositiveIntegerField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['data_validade'],
            },
        ),
        migrations.CreateModel(
            name='TipoImunobiologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('doses_necessarias', models.PositiveIntegerField(default=1)),
                ('intervalo_doses', models.PositiveIntegerField(default=0, help_text='Intervalo em dias')),
                ('publico_alvo', models.CharField(choices=[('TODOS', 'Todos'), ('CRIANCAS', 'Crianças'), ('ADOLESCENTES', 'Adolescentes'), ('ADULTOS', 'Adultos'), ('IDOSOS', 'Idosos'), ('GESTANTES', 'Gestantes')], default='TODOS', max_length=20)),
                ('tempo_validade_apos_aberto', models.PositiveIntegerField(help_text='Tempo em horas após abertura do frasco')),
                ('doses_por_frasco', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueImunobiologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_frascos', models.PositiveIntegerField()),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidades.unidadesaude')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.lote')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAbertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('doses_utilizadas', models.PositiveIntegerField(default=0)),
                ('doses_perdidas', models.PositiveIntegerField(default=0)),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.estoqueimunobiologico')),
            ],
        ),
        migrations.AddField(
            model_name='lote',
            name='tipo_imunobiologico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.tipoimunobiologico'),
        ),
    ]
