# Generated by Django 5.2 on 2025-04-13 05:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        ('unidades', '0002_bairro_alter_unidadesaude_bairro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='quantidade_frascos_central',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroabertura',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registroabertura',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registroabertura',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DistribuicaoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_frascos', models.PositiveIntegerField()),
                ('data_distribuicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.lote')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidades.unidadesaude')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_distribuicao'],
            },
        ),
    ]
