# Generated by Django 5.2 on 2025-04-12 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('unidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DISPONIBILIDADE', 'Vacina Disponível'), ('VENCIMENTO', 'Alerta de Vencimento'), ('ESTOQUE_BAIXO', 'Estoque Baixo'), ('SISTEMA', 'Mensagem do Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificar_email', models.BooleanField(default=True)),
                ('notificar_app', models.BooleanField(default=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidades.municipio')),
                ('tipo_imunobiologico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.tipoimunobiologico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'tipo_imunobiologico', 'municipio')},
            },
        ),
    ]
