# Generated by Django 5.2 on 2025-04-12 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bairros', to='unidades.municipio')),
            ],
            options={
                'ordering': ['municipio', 'nome'],
                'unique_together': {('nome', 'municipio')},
            },
        ),
        migrations.AlterField(
            model_name='unidadesaude',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to='unidades.bairro'),
        ),
    ]
